#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

jupyter labextension install jupyter-offlinenotebook

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/
mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#                 kafka-related commands                      #
###############################################################
export KAFKA_VERSION=2.7.0
echo "export KAFKA_VERSION=${KAFKA_VERSION}" >> ~/.bashrc
echo "export KAFKA_VERSION=${KAFKA_VERSION}" >> ~/.profile

export KAFKA_HOME=$(pwd)/kafka-${KAFKA_VERSION}
echo "export KAFKA_HOME=${KAFKA_HOME}" >> ~/.bashrc
echo "export KAFKA_HOME=${KAFKA_HOME}" >> ~/.profile

wget https://www-eu.apache.org/dist/kafka/${KAFKA_VERSION}/kafka_2.12-${KAFKA_VERSION}.tgz -q 	    && \
tar -xvf kafka_2.12-${KAFKA_VERSION}.tgz > /dev/null 										 		&& \
rm       kafka_2.12-${KAFKA_VERSION}.tgz															&& \
mv 		 kafka_2.12-${KAFKA_VERSION}	kafka-${KAFKA_VERSION}

# adding bin/ to $path
echo "export PATH=\$PATH:\$KAFKA_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$KAFKA_HOME/bin"   >> ~/.profile

###############################################################
#                 spark-related commands                      #
###############################################################
export SPARK_VERSION=3.0.1
echo "export SPARK_VERSION=${SPARK_VERSION}" >> ~/.bashrc
echo "export SPARK_VERSION=${SPARK_VERSION}" >> ~/.profile

export SPARK_HOME=$(pwd)/spark-${SPARK_VERSION}
echo "export SPARK_HOME=${SPARK_HOME}" >> ~/.bashrc
echo "export SPARK_HOME=${SPARK_HOME}" >> ~/.profile

wget https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop2.7.tgz               && \
tar -xvf spark-${SPARK_VERSION}-bin-hadoop2.7.tgz > /dev/null 										 		              && \
rm       spark-${SPARK_VERSION}-bin-hadoop2.7.tgz															              && \
mv 		 spark-${SPARK_VERSION}-bin-hadoop2.7	spark-${SPARK_VERSION}

# adding bin/ to $path
echo "export PATH=\$PATH:\$SPARK_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$SPARK_HOME/bin"   >> ~/.profile

###############################################################
#                 minio-related commands                      #
###############################################################
wget https://dl.min.io/server/minio/release/linux-amd64/minio
wget https://dl.min.io/client/mc/release/linux-amd64/mc

# adding mc to $path
echo "export PATH=\$PATH:\$(pwd)/resources/local/"   >> ~/.bashrc
echo "export PATH=\$PATH:\$(pwd)/resources/local/"   >> ~/.profile

###############################################################
#                 airflow-related commands                      #
###############################################################
export AIRFLOW_HOME=$(pwd)/airflow
echo "export AIRFLOW_HOME=${AIRFLOW_HOME}" >> ~/.bashrc
echo "export AIRFLOW_HOME=${AIRFLOW_HOME}" >> ~/.profile
